services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=bancoInvestimentos'
      - 'MYSQL_PASSWORD=bank'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=usuarioPadrao'
    ports:
      - '3307:3306'